source 'https://rubygems.org'

gem 'bundler'
gem 'grape'
gem 'json'
gem 'rails'
gem 'g'
# gem 'gengiscan', ">=0.40"
# gem 'rake', :groups=>[:development, :test]
gem 'rack-test', :group=>:test
gem 'rspec', :group=>:test
